import assert from "node:assert/strict";
import { chromium, expect } from "@playwright/test";
import sharp from "sharp";
import { mkdir } from "node:fs/promises";
const browser = await chromium.launch({ headless: true, channel: "msedge" });
const page = await browser.newPage({ viewport: { width: 390, height: 844 } });
const photo = { name: "taste.jpg", mimeType: "image/jpeg", buffer: await sharp({ create: { width: 600, height: 300, channels: 3, background: "#edbda6" } }).jpeg().toBuffer() };
const analysis = { readable: true, tags: ["노을", "실루엣", "탁 트인 배경"], background: "탁 트인 하늘", mood: "따뜻한 색조", composition: "역광 인물", uncertainty: "원하는 요소를 직접 확인해 주세요." };
let mode = "success", calls = 0;
let release: (() => void) | undefined;
try {
  await page.route("**/api/auth/session", (r) => r.fulfill({ json: null }));
  await page.route("**/api/photo-preferences/analyze", async (r) => {
    calls++;
    if (mode === "failure") return r.fulfill({ status: 503, json: { error: "사진 분석 설정이 준비되지 않았습니다. 직접 선택해 주세요." } });
    if (mode === "late") await new Promise<void>((resolve) => { release = resolve; });
    await r.fulfill({ json: { analysis: mode === "unreadable" ? { ...analysis, readable: false, tags: [] } : analysis } }).catch(() => {});
  });
  await page.goto("http://localhost:3104/photo");
  const area = page.getByRole("region", { name: "촬영 취향 확인", exact: true });
  const form = area.getByRole("form", { name: "촬영 취향 입력" });
  const album = area.getByLabel("참고 사진 앨범 파일");
  const analyze = area.getByRole("button", { name: "사진 분석", exact: true });
  const save = form.getByRole("button", { name: "이 취향으로 확정" });
  const status = area.getByText("촬영 취향을 확정했습니다.", { exact: true });
  await save.click();
  await expect(area.getByRole("alert")).toContainText("1개 이상");
  await form.getByRole("checkbox", { name: "벽화", exact: true }).check();
  await save.click(); await expect(status).toBeVisible(); assert.equal(calls, 0);
  await form.getByLabel("가장 중요한 요소").selectOption("background");
  await expect(status).toHaveCount(0);
  await form.getByLabel("선호 설명", { exact: false }).fill("색감보다 배경이 좋아요.");
  await save.click(); await expect(status).toBeVisible();
  await album.setInputFiles(photo);
  await expect(status).toHaveCount(0);
  await expect(form.getByRole("checkbox", { name: "벽화", exact: true })).not.toBeChecked();
  assert.equal(calls, 0);
  await analyze.click();
  await expect(area.getByText("사진 취향 제안 · 확인 전")).toBeVisible();
  await expect(status).toHaveCount(0);
  await expect(form.getByRole("checkbox", { name: "노을", exact: true })).toBeChecked();
  await form.getByRole("checkbox", { name: "실루엣", exact: true }).uncheck();
  await form.getByRole("checkbox", { name: "인물", exact: true }).check();
  await form.getByLabel("가장 중요한 요소").selectOption("background");
  await form.getByLabel("선호 설명", { exact: false }).fill("색감보다 배경이 좋아요.");
  await save.click(); await expect(status).toBeVisible();
  await expect(area.getByRole("status")).toContainText("노을 · 탁 트인 배경 · 인물");
  assert.deepEqual(await page.evaluate(() => Object.keys(localStorage)), []);
  await mkdir("test-results", { recursive: true });
  await page.screenshot({ path: "test-results/photo-preferences-mobile.png", fullPage: true });
  await form.getByRole("button", { name: "취향 초기화" }).click();
  await expect(status).toHaveCount(0);
  mode = "failure"; await analyze.click();
  await expect(area.getByRole("alert")).toContainText("직접 선택");
  await form.getByRole("checkbox", { name: "골목", exact: true }).check();
  await save.click(); await expect(status).toBeVisible();
  mode = "unreadable"; await analyze.click();
  await expect(area.getByText("사진에서 취향을 파악하기 어렵습니다.", { exact: false })).toBeVisible();
  await expect(status).toHaveCount(0);
  await expect(form.locator("input:checked")).toHaveCount(0);
  mode = "late"; await analyze.click();
  await expect.poll(() => !!release).toBe(true);
  await area.getByRole("button", { name: "사진 삭제", exact: true }).click(); release!();
  await expect(area.getByText("사진 취향 제안 · 확인 전")).toHaveCount(0);
  await expect(analyze).toBeDisabled();
  await form.getByRole("checkbox", { name: "야경", exact: true }).check();
  await save.click(); await expect(status).toBeVisible();
  await page.reload();
  await expect(status).toHaveCount(0);
  await expect(form.locator("input:checked")).toHaveCount(0);
  console.log("PASS 수동 선택·미전송·빈 태그 검증·분석 초안·태그 수정·선호 설명·확정 무효화·실패 직접 입력·판독불가·지연응답 폐기·새로고침 초기화");
} finally { release?.(); await browser.close(); }
