import assert from "node:assert/strict";
import { chromium, expect } from "@playwright/test";
import { mkdir } from "node:fs/promises";
import { createPhotoCourse } from "../src/lib/services/photo-course";
import { photoCourseRequestSchema } from "../src/lib/photo-course";
const browser = await chromium.launch({ headless: true, channel: "msedge" });
const page = await browser.newPage({ viewport: { width: 390, height: 844 } });
const now = new Date("2026-09-17T03:55:00Z");
let mode = "success";
let release: (() => void) | undefined;
try {
  await page.clock.setFixedTime(now);
  await page.route("**/api/auth/session", (r) => r.fulfill({ json: null }));
  await page.route("**/api/photo-courses", async (r) => {
    if (mode === "failure") return r.fulfill({ status: 503, json: { error: "이동 경로를 확인하지 못했습니다." } });
    if (mode === "late") await new Promise<void>((resolve) => { release = resolve; });
    const input = photoCourseRequestSchema.parse(r.request().postDataJSON());
    const course = await createPhotoCourse(input, { leg: async () => ({ minutes: 15, estimated: true }) }, now);
    await r.fulfill({ json: { course } }).catch(() => {});
  });
  await page.goto("http://localhost:3104/photo");
  const pref = page.getByRole("form", { name: "촬영 취향 입력" });
  const planner = page.getByRole("region", { name: "포토 코스 생성", exact: true });
  await expect(planner.getByText("위에서 촬영 취향을 먼저 확정해 주세요.")).toBeVisible();
  await pref.getByRole("checkbox", { name: "노을", exact: true }).check();
  await pref.getByRole("checkbox", { name: "인물", exact: true }).check();
  await pref.getByLabel("선호 설명", { exact: false }).fill("가".repeat(500));
  await pref.getByRole("button", { name: "이 취향으로 확정" }).click();
  const form = planner.getByRole("form", { name: "포토 여행 조건" });
  const configure = async () => {
    await form.getByLabel("방문 날짜").fill("2026-09-17");
    await form.getByLabel("출발 시각", { exact: false }).fill("13:00");
    await form.getByLabel("여행 시간(분)", { exact: true }).fill("420");
  };
  const generate = form.getByRole("button", { name: "포토 코스 생성", exact: true });
  const proposal = planner.getByRole("region", { name: "포토 코스 제안" });
  await configure(); await generate.click();
  await expect(proposal).toBeVisible();
  await expect(proposal.getByRole("heading", { name: /수성못/ })).toBeVisible();
  assert.equal(await page.evaluate(() => localStorage.getItem("motion.active-trip.v1")), null);
  await expect(proposal.getByRole("button", { name: "이 코스로 여행 시작" })).toBeDisabled();
  await form.getByLabel("여행 제목").fill("수정한 제목");
  await expect(proposal).toHaveCount(0);
  mode = "failure"; await generate.click();
  await expect(planner.getByRole("alert")).toContainText("이동 경로");
  mode = "late"; await generate.click();
  await expect.poll(() => !!release).toBe(true);
  await pref.getByRole("checkbox", { name: "벽화", exact: true }).check();
  release!();
  await expect(planner.getByText("위에서 촬영 취향을 먼저 확정해 주세요.")).toBeVisible();
  await pref.getByRole("button", { name: "이 취향으로 확정" }).click();
  mode = "success"; await configure(); await generate.click();
  await expect(proposal).toBeVisible();
  await proposal.getByRole("checkbox").check();
  await mkdir("test-results", { recursive: true });
  await page.screenshot({ path: "test-results/photo-course-mobile.png", fullPage: true });
  await proposal.getByRole("button", { name: "이 코스로 여행 시작" }).click();
  const active = page.getByRole("region", { name: "진행 중 여행", exact: true });
  await expect(active).toBeVisible();
  const saved = await page.evaluate(() => JSON.parse(localStorage.getItem("motion.active-trip.v1")!));
  assert.equal(saved.photoTaste.note.length, 500);
  assert.equal(saved.stops.length, 3);
  assert.ok(saved.stops.every((s: { photoGuide?: object }) => s.photoGuide));
  assert.equal(saved.parking ?? null, null);
  await generate.click();
  await expect(proposal.getByRole("button", { name: "이 코스로 여행 시작" })).toBeDisabled();
  await page.reload();
  await expect(active).toBeVisible();
  assert.deepEqual(await page.evaluate(() => JSON.parse(localStorage.getItem("motion.active-trip.v1")!)), saved);
  console.log("PASS 확정 취향 필수·코스 생성·미리보기 보존·조건 변경 무효화·실패 재시도·늦은 응답 폐기·확인 후 시작·500자 설명/촬영 안내 복원·기존 여행 보호");
} finally { release?.(); await browser.close(); }
