import assert from "node:assert/strict";
import { chromium, expect } from "@playwright/test";
import sharp from "sharp";
import { mkdir } from "node:fs/promises";
const browser = await chromium.launch({ headless: true, channel: "msedge" });
const page = await browser.newPage({ viewport: { width: 390, height: 844 } });
const trip = { version: 1, id: "scene-trip", sourceRunId: "run", title: "현장 사진 검증", revision: 0, status: "active", startedAt: "2026-09-17T00:00:00.000Z", updatedAt: "2026-09-17T00:00:00.000Z", transportMode: "walk", remainingMinutes: 180, stops: [{ id: "a", name: "방문한 장소", address: null, latitude: 35.87, longitude: 128.6, visitedAt: "2026-09-17T00:00:00.000Z" }, { id: "b", name: "남은 장소", address: null, latitude: 35.88, longitude: 128.61, visitedAt: null }] };
const photo = { name: "scene.jpg", mimeType: "image/jpeg", buffer: await sharp({ create: { width: 600, height: 300, channels: 3, background: "#d8eee8" } }).jpeg().toBuffer() };
const analysis = { readable: true, observedText: "9월 17일 임시 휴무", reason: "closed", detail: "임시 휴무 안내가 보입니다.", uncertainty: "오늘에 해당하는지 날짜와 대상 장소를 확인해 주세요." };
let mode = "success", calls = 0;
let release: (() => void) | undefined;
try {
  await page.route("**/api/auth/session", (r) => r.fulfill({ json: null }));
  await page.addInitScript((seed) => { localStorage.setItem("motion.active-trip.v1", JSON.stringify(seed)); }, trip);
  await page.route("**/api/trips/scene-photo", async (r) => {
    calls++;
    assert.equal(r.request().headers()["content-type"], "image/jpeg");
    if (mode === "failure") return r.fulfill({ status: 503, json: { error: "사진 분석 설정이 준비되지 않았습니다. 상황을 직접 입력해 주세요." } });
    if (mode === "late") await new Promise<void>((resolve) => { release = resolve; });
    await r.fulfill({ json: { analysis: mode === "unreadable" ? { ...analysis, readable: false, reason: "other", detail: "" } : analysis } }).catch(() => {});
  });
  await page.goto("http://localhost:3104/login");
  const group = page.getByRole("group", { name: "현장 사진 분석", exact: true });
  const album = group.getByLabel("현장 사진 앨범 파일");
  const analyze = group.getByRole("button", { name: "사진 분석", exact: true });
  const form = page.getByRole("form", { name: "현장 상황 입력" });
  const stored = () => page.evaluate(() => JSON.parse(localStorage.getItem("motion.active-trip.v1")!));
  await album.setInputFiles(photo);
  assert.equal(calls, 0);
  await analyze.click();
  await expect(group.getByText("분석 결과 · 확인 전 초안")).toBeVisible();
  assert.deepEqual(await stored(), trip);
  await group.getByRole("button", { name: "상황 입력에서 확인·수정" }).click();
  await expect(form.getByLabel("상황 설명", { exact: false })).toHaveValue(analysis.detail);
  await expect(form.getByLabel("변경 대상 장소")).toHaveValue("");
  await expect(form.getByRole("button", { name: "상황 저장", exact: true })).toBeDisabled();
  await group.getByRole("button", { name: "사진 삭제", exact: true }).click();
  await expect(form).toHaveCount(0);
  await expect(group.getByText("분석 결과 · 확인 전 초안")).toHaveCount(0);
  assert.deepEqual(await stored(), trip);
  await album.setInputFiles(photo);
  mode = "failure"; await analyze.click();
  await expect(group.getByRole("alert")).toContainText("직접 입력");
  mode = "unreadable"; await analyze.click();
  await expect(group.getByText("상황을 판독하기 어렵습니다.", { exact: false })).toBeVisible();
  await expect(group.getByRole("button", { name: "상황 입력에서 확인·수정" })).toHaveCount(0);
  mode = "late"; await analyze.click();
  await expect.poll(() => !!release).toBe(true);
  await group.getByRole("button", { name: "사진 삭제", exact: true }).click();
  release!();
  await expect(group.getByText("분석 결과 · 확인 전 초안")).toHaveCount(0);
  mode = "success"; await album.setInputFiles(photo); await analyze.click();
  await group.getByRole("button", { name: "상황 입력에서 확인·수정" }).click();
  await form.getByLabel("상황 설명", { exact: false }).fill("직접 확인한 오늘 휴무 안내입니다.");
  await form.getByLabel("변경 대상 장소").selectOption("b");
  await form.getByLabel("또는 지금 있는 코스 장소").selectOption("a");
  await form.getByRole("checkbox").check();
  await mkdir("test-results", { recursive: true });
  await page.screenshot({ path: "test-results/scene-photo-confirmation.png", fullPage: true });
  assert.deepEqual(await stored(), trip);
  await form.getByRole("button", { name: "상황 저장", exact: true }).click();
  await expect(page.getByText("저장한 상황: 휴무예요", { exact: true })).toBeVisible();
  const saved = await stored();
  assert.equal(saved.situation.detail, "직접 확인한 오늘 휴무 안내입니다.");
  assert.deepEqual(saved.stops, trip.stops);
  assert.equal(JSON.stringify(saved).includes("observedText"), false);
  assert.equal(JSON.stringify(saved).includes("base64"), false);
  console.log("PASS 선택만으로 미전송·확인 전 여행 보존·초안 수정/대상 필수·삭제 무효화·실패 재시도·판독불가·지연응답 폐기·사용자 확인 후 상황 저장");
} finally { release?.(); await browser.close(); }
